steps:
  - name: node:22
    entrypoint: bash
    args:
      - -c
      - npm install -g pnpm@10.6.1 && pnpm install && pnpm build
  - name: node:22
    entrypoint: npm
    args: ['install', '-g', 'firebase-tools']
  - name: 'node:22'
    entrypoint: './node_modules/.bin/firebase'
    args: ['deploy', '--project', '$PROJECT_ID']
