steps:
  - name: node:22
    entrypoint: bash
    args:
      - -c
      - npm install -g pnpm@10.6.1 && pnpm install && pnpm build && pnpm exec firebase experiments:enable webframeworks && pnpm exec firebase deploy --only hosting
