name: "Automerge Dependabot"

on:
  pull_request:
  push:
    branches: 
      - raph84-blog-dependabot

jobs:
  worker:
    runs-on: ubuntu-latest

    #if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test:ci
        env:
          CI: true
#      - uses: actions/github-script@0.2.0
#        with:
#          script: |
#            github.pullRequests.createReview({
#              owner: context.payload.repository.owner.login,
#              repo: context.payload.repository.name,
#              pull_number: context.payload.pull_request.number,
#              event: 'APPROVE'
#            })
#            github.pullRequests.merge({
#              owner: context.payload.repository.owner.login,
#              repo: context.payload.repository.name,
#              pull_number: context.payload.pull_request.number
#            })
#          github-token: ${{github.token}}
